import './js/modal';
import './js/scrollUp';
import './js/exercisesLeft';
import './js/exercisesRightSecondPart';
import './js/exercisesRightFirstPart';
import './js/pagination';
import './js/header';
import './js/footer';
import './js/give-rating'